### ISSUE TITLE
Getting PhoneBook error with FritzOS 7

### ISSUE THREAD

**Issue by jlp2** [b-jesch/service.fritzbox.callmonitor#11]
There is a new problem with FritzOS 7.
There must be some changes with the location of the Phonebooks.
This is on a 7490 with FritzOS 7.01
Now the following error occurred:

```
08:46:12.545 T:140315282159360  NOTICE: [service.fritzbox.callmonitor] Settings loaded
08:46:12.545 T:140315282159360  NOTICE: [service.fritzbox.callmonitor] Looking for all phonebook modules in /home/xbmc/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks
08:46:12.545 T:140315282159360  NOTICE: [service.fritzbox.callmonitor] Found module file, import resources.lib.PhoneBooks.PytzBox
08:46:12.863 T:140315282159360  NOTICE: [service.fritzbox.callmonitor] Yield phonebook module PytzBox
08:46:12.864 T:140315282159360  NOTICE: [service.fritzbox.callmonitor] Found module file, import resources.lib.PhoneBooks.AppleCloud
08:46:12.883 T:140315282159360  NOTICE: [service.fritzbox.callmonitor] Yield phonebook module AppleCloud
08:46:13.221 T:140314207446784  NOTICE: AddOnLog: VDR VNSI Client: Logged in at '1536993973+7200' to 'VDR-Network-Streaming-Interface (VNSI) Server' Version: '1.5.2' with protocol version '12'
08:46:13.297 T:140314014635776  NOTICE: PVRManager - stopping
08:46:13.562 T:140315264866048  NOTICE: Start - EPG thread started
08:46:13.896 T:140315282159360   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'resources.lib.PhoneBooks.PhoneBookBase.RequestFailedException'>
                                            Error Contents: Failed to parse: fritz.box:49000"&sid=ca9d54eb08ff4a25
                                            Traceback (most recent call last):
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/default.py", line 385, in <module>
                                                CallMon = FritzCallmonitor()
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/default.py", line 98, in __init__
                                                self.getPhonebook()
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/default.py", line 154, in getPhonebook
                                                self.__phonebook = self.__phoneBookFacade.getPhonebook()
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks/PhoneBookFacade.py", line 88, in getPhonebook
                                                phone_books.update(phone_book.getPhonebook())
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks/PytzBox.py", line 149, in getPhonebook
                                                result.update(self.getPhonebook(pbid=this_id))
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks/PytzBox.py", line 191, in getPhonebook
                                                return self.__analyzeFritzboxPhonebook(xml_phonebook)
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks/PytzBox.py", line 88, in __analyzeFritzboxPhonebook
                                                self.cacheImages(handler.phone_book[item]['imageBMP'], handler.phone_book[item]['numbers'])
                                              File "/home/xbmc/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks/PytzBox.py", line 107, in cacheImages
                                                raise self.RequestFailedException(e.message)
                                            RequestFailedException: Failed to parse: fritz.box:49000"&sid=ca9d54eb08ff4a25
                                            -->End of Python script error report<--
08:46:53.825 T:140316419188480   ERROR: GetDirectory - Error getting
```

**Comment by jlp2** [comment]
I forgot to mention that this is the call for the external phonebook (google contacts), the internal seemed to be ok..

**Comment by robsy** [comment]
Same issue at my installation.

**Comment by franky384** [comment]
Same here, since update to Fritzos 7.01 on Fritzbox7362sl

**Comment by b-jesch** [comment]
For the moment I recommended that you don't use external phonebooks. I own a FB 7362sl too (with OS 7.0.). I'll update to 7.01 in the next days and probably investigate time to fix. Be patient, it's christmas time.

**Comment by franky384** [comment]
Thank you for your fast reply and happy christmas !

**Comment by b-jesch** [comment]
Crash fixed while using external phonebooks (e.g. Google Contacts) and FritzOS 7.01. Online images will not be loaded yet. New version will be uploaded in saXBMC Repo soon. Meanwhile you can download this still from Git here.
