### ISSUE TITLE
Import error with module six

### ISSUE THREAD

**Issue by b-jesch** [b-jesch/service.fritzbox.callmonitor#4]
Another import error on a fresh LibreELEC Installation appeared (LE 7.90.003 - Krypton):

`
08:00:02 T:140104929941248   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named six
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.fritzbox.callmonitor/default.py", line 12, in <module>
                                                from resources.lib.PhoneBooks.PhoneBookFacade import PhoneBookFacade
                                              File "/storage/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks/PhoneBookFacade.py", line 8, in <module>
                                                from PhoneBookBase import PhoneBookBase
                                              File "/storage/.kodi/addons/service.fritzbox.callmonitor/resources/lib/PhoneBooks/PhoneBookBase.py", line 2, in <module>
                                                from six import with_metaclass
                                            ImportError: No module named six
                                            -->End of Python script error report<--
`

**Comment by b-jesch** [comment]
Hope this is resolved with https://github.com/b-jesch/service.fritzbox.callmonitor/commit/74d63e902b7bc5c0067653a846757d828eebbdaf?diff=unified

**Comment by b-jesch** [comment]
Yepp, closed

**Comment by lutzleonhardt** [comment]
Great, thx for the fix.
